# Generated by Django 3.1.1 on 2020-09-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coverapp', '0003_add_customer_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_transections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('date_of_dr', models.DateField(blank=True, null=True)),
                ('date_of_cr', models.DateField(blank=True, null=True)),
                ('dr_amount', models.FloatField(blank=True, null=True)),
                ('cr_amount', models.FloatField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coverapp.add_customer')),
            ],
        ),
    ]
