# Generated by Django 3.1.1 on 2020-10-01 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coverapp', '0004_customer_transections'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_transections',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer_transections',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coverapp.add_customer'),
        ),
    ]
