# Generated by Django 3.1.1 on 2020-10-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverapp', '0005_auto_20201002_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_transections',
            old_name='customer',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='customer_transections',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
