# Generated by Django 3.1.1 on 2020-10-02 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverapp', '0006_auto_20201002_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_transections',
            old_name='dr_amount',
            new_name='amount_of_goods',
        ),
        migrations.RenameField(
            model_name='customer_transections',
            old_name='date_of_dr',
            new_name='date_of_send_goods',
        ),
    ]
