# Generated by Django 3.1.1 on 2020-10-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverapp', '0007_auto_20201002_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_transections',
            old_name='customer_name',
            new_name='customer_shop_name',
        ),
    ]
