# Generated by Django 3.1.1 on 2020-10-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverapp', '0008_auto_20201002_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_transections',
            name='user_id',
        ),
    ]
