# Generated by Django 3.1.1 on 2020-10-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverapp', '0009_remove_customer_transections_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_transections',
            name='amount_of_goods',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='customer_transections',
            name='cr_amount',
            field=models.FloatField(default=''),
        ),
    ]
