# Generated by Django 3.1.1 on 2020-10-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverapp', '0010_auto_20201013_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_transections',
            name='amount_of_goods',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer_transections',
            name='cr_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
